### ISSUE TITLE
Error regarding "category" slot from Biolink in SchemaSheets 

### ISSUE THREAD

**Issue by puja-trivedi** [brain-bican/bkbit#51]
Fix how `slot_usage:category` is used in schemasheets. When using schemasheets for assertion_evidence model `slot_usage:category` is automatically added in the model; therefore, we get a linkml validation error saying: `category is not defined in the model`. This issue will occur with all models we define in the future if they do not define `category` or import from biolink.

Note: `category` is a slot inherited from biolink.

**Comment by djarecka** [comment]
fixed by #53
